PROGRAM
	'Freeze_Intervention.ab sequentially moves Y by +DY then X by +DX to extract the capillary 
	'from the cooling stream of the temperature controller. Once extracted, it sets 
	'IGLOBAL(3) = 1 to trigger 90-deg rotation of the peristaltic pump. Once this motion is 
	'complete, IGLOBAL(3) is set to 0, and the capillary returns to its original position.
    'Hint for the EPICS IOC which program is currently running
	'(UserString0 if in task 1, UserString1 if in auxiliary task)
	SETPARM UserString1,"Freeze_Intervention.ab"
	
	ABS
	'SCOPEBUFFER 1200
	'SCOPETRIGPERIOD 1	' -4 (-2) corresponds to 4 (2) kHz
	'SCOPETRIG
	
	DX = 3
	DY = 11
	
	RAMP MODE RATE
	RAMP RATE Y 5000
	RAMP RATE X 500
	WAIT MODE MOVEDONE
	'
	MOVEINC Y DY YF 200
	MOVEINC X DX XF 200
	
	IGLOBAL(3) = 1
	
	WHILE IGLOBAL(3) > 0 'Set IGLOBAL(3) = 0 to exit loop
		DWELL 0.1
		'IGLOBAL(3) = 0 'This line mimics what PVT_Fly-thru does.
	WEND
	DWELL 2	'After flushing, wait time before reinsertion
	
	MOVEINC X -1*DX
	MOVEINC Y -1*DY
	
END PROGRAM