' ------------------------------------------------ 
' --------------- PVT_even_odd.ab -----------------
' ------------------------------------------------ 
'
' This program moves in a repetitive staircase
' fashion. 
'
Z_0 = 12.6 'starting Z position
DZ = 0.6096		'slot separation
DT = 0.024304558/2	'Staircase Period
Nslots = 41
Nrepeats = 2

'Initial setup
IF AXISFAULT(Z) <> 0 THEN
    FAULTACK Z 'Make sure any fault state is cleared.
END IF
ENABLE Z
DIM homed AS INTEGER
homed = (AXISSTATUS(Z) >> 1) BAND 1
IF NOT homed THEN 'make sure axis is homeds
    HOME Z
END IF
MOVEABS Z Z_0 'Got to starting position
WAIT MOVEDONE Z

ABS 'Positions specified in absolute coordinates.s

WHILE 1
	
	loopcount = 0
	WAIT MOVEDONE Z
	
	'STARTSYNC -1 ' -1 sets period to 500 us 
	WHILE DIN(X,1,0)=0 
		'SYNC
		DWELL 0.0005
		loopcount=loopcount+1
	WEND
	PVT INIT TIME ABS
    HALT

	FOR j = 0 TO Nrepeats-1
		FOR i = 0 TO Nslots-1	
			IF i < 21
				THEN Zi = Z_0-2*i*DZ
				ELSE Zi = Z_0-(2*(Nslots-i)-1)*DZ
			END IF
			Ti1 = (2*j*Nslots+2*i+1)*DT
			Ti2 = (2*j*Nslots+2*i+2)*DT
			IF i = 0
				THEN 
					PVT Z Zi, 0 TIME Ti1 DOUT X,1,1,1
					PVT Z Zi, 0 TIME Ti2 DOUT X,1,0,1
				ELSE
					PVT Z Zi, 0 TIME Ti1
					PVT Z Zi, 0 TIME Ti2
			END IF
		NEXT i
	NEXT j
	'DIM PrintString AS STRING(80)
	'FORMAT PrintString, "%d\n", INTV:loopcount
	'PRINT PrintString
WEND