counter_name = 'temperature_controller'
Size = wx.Size(707, 344)
logfile = '/net/mx340hs/data/anfinrud_1710/Logfiles/Test-2.log'
average_count = 1
max_value = nan
min_value = nan
end_fraction = 1
reject_outliers = False
outlier_cutoff = 2.5
show_statistics = True
time_window = 30
