counter_name = 'y'
Size = wx.Size(640, 480)
logfile = '/Mirror/Femto/C/All Projects/APS/Experiments/2014.11/Logfiles/Beamstop-test-5.log'
average_count = 1
max_value = nan
min_value = nan
start_fraction = 0.997
reject_outliers = False
outlier_cutoff = 2.5
show_statistics = True
time_window = 600
