show_in_list = True
title = 'Diagnostics Configuration'
motor_names = ['diagnostics.list']
names = ['diagnostics']
motor_labels = ['diagnostics']
widths = [300]
line0.description = 'SAXS/WAXS'
line1.description = 'NIH:Channel-Cut-Scan'
line0.updated = '25 Oct 17:31'
line1.updated = '25 Oct 17:31'
line0.diagnostics.list = 'ring_current, bunch_current, temperature'
line1.diagnostics.list = 'xscope.P1, xscope.P2'
command_row = 0
show_define_buttons = False
command_rows = [0]
nrows = 4
line2.description = 'NIH:Slit-Scan'
line2.diagnostics.list = 'xscope.P3'
line2.updated = '2019-01-28 19:21:13'
line3.description = 'Rob Test'
description_width = 170
line3.diagnostics.list = 'xscope.P1'
line3.updated = '2019-02-04 11:31:36'