title = 'Scan Configuration'
motor_names = ['collect.scan_points', 'collect.scan_return', 'collect.scan_relative', 'collect.scan_motor_name']
widths = [200, 55, 55, 100]
names = ['points', 'return', 'relative', 'motors']
motor_labels = ['list of values', 'return', 'relative', 'motor']
line0.description = 'Laue Crystallography'
line0.collect.scan_points = 'arange(0,180,5)'
line0.collect.scan_return = '0'
line0.collect.scan_relative = '0'
line0.collect.scan_motor = 'Phi'
description_width = 200
line1.description = 'NIH:Channel-Cut-Scan'
line1.collect.scan_points = 'arange(8,14,0.01)'
line1.collect.scan_return = 1.0
line1.collect.scan_relative = 0
line1.collect.scan_motor = 'Energy'
line0.updated = '23 Oct 4:02'
line1.updated = '2019-01-29 19:28:50'
command_row = 2
line0.collect.scan_motor_string = 'Phi'
line1.collect.scan_motor_string = 'Energy'
line1.collect.scan_motor_name = 'Energy'
line0.collect.scan_motor_name = 'Phi'
formats = ['%s', '%d', '%d', '%s']
nrows = 7
line2.description = 'NIH:Overlap_scan_Z'
line2.collect.scan_return = 1.0
line2.collect.scan_relative = 1.0
command_rows = []
multiple_selections = False
line2.updated = '03 Nov 15:42'
line2.collect.scan_points = 'arange(-0.6,0.6,0.05)'
line2.collect.scan_motor_name = 'LaserZ'
line3.description = 'NIH:Overlap_scan_X'
line3.collect.scan_points = 'arange(-0.2,0.2,0.02)'
line3.updated = '03 Nov 15:44'
line3.collect.scan_return = 1.0
line3.collect.scan_relative = 1.0
line3.collect.scan_motor_name = 'LaserX'
row_height = 23
line4.description = 'NIH:Slit-Scan-Z'
line4.collect.scan_points = 'arange(-0.4,0.4,0.02)'
line4.collect.scan_return = 1.0
line4.collect.scan_relative = 1.0
line4.collect.scan_motor_name = 'GonZ'
line4.updated = '2019-01-28 19:39:25'
line5.description = 'NIH:Slit-Scan-Y'
line5.collect.scan_points = 'arange(-2,2,0.05)'
line5.updated = '2019-01-28 22:06:06'
line5.collect.scan_return = 1.0
line5.collect.scan_relative = 1.0
line5.collect.scan_motor_name = 'GonY'
line6.collect.scan_points = 'arange(11.9,12.0,0.002)'
line6.updated = '2019-03-19 17:09:57'
line6.collect.scan_return = 1
line6.collect.scan_relative = 0
line6.collect.scan_motor_name = 'Energy'
line6.description = 'NIH:Channel-Cut-Scan Calib.'