' ------------------------------------------------ 
' --------------- PVT_even_odd.ab -----------------
' ------------------------------------------------ 
'
' This program moves in a repetitive staircase
' fashion. 
'
'synchronize at 12.28 mm
'velocity is 75 mm/ms at 12.28 mm
'

DGLOBAL(0) = 0 'time offset to synchronize
DGLOBAL(1) = 0 'counter for computing <PMCD(Z)>

Z_0 = 12.54 'starting Z position
DZ = 0.610		'slot separation
DT = 0.024304558	'Staircase Period
DT = 0.999998412*DT
Z_synch = Z_0-0.3 'Vmax between slots 1 and 0

Nslots = 41

'SETGAIN <Axis>, <GainKp>, <GainKi>, <GainKpos>, <GainAff>
'SETGAIN sets all 4 parameters synchronously
SETGAIN Z, 1780000, 10000, 100, 56200
SETPARM Z, GainVff, 2371

DIM PrintString AS STRING(80)

'Initial setup
IF AXISFAULT(Z) <> 0 THEN
    FAULTACK Z 'Make sure any fault state is cleared.
END IF
ENABLE Z
DIM homed AS INTEGER
homed = (AXISSTATUS(Z) >> 1) BAND 1
IF NOT homed THEN 'make sure axis is homeds
    HOME Z
END IF
MOVEABS Z Z_0 'Got to starting position
WAIT MOVEDONE Z

ABS 'Positions specified in absolute coordinates.s
PVT INIT TIME ABS
HALT

WHILE DIN(X,1,0)=0 'wait for clk pulse 
	DWELL 0.00025 
WEND
DWELL 0.972	'0.971, 0.980 with Task 1 only


j = 0
WHILE 1
	FOR i = 0 TO Nslots-1
		PumpA_pos = j*1.8
		T_0 = j*43*DT+DGLOBAL(0)
		Zi = Z_0-i*DZ
		Ti1 = T_0+(i+0.4)*DT+DGLOBAL(0)
		Ti2 = T_0+(i+1)*DT+DGLOBAL(0)
		IF i = 40
			THEN 
				PVT Z Zi, 0 TIME Ti1 DOUT X,1,0,1
				PVT Z Zi, 0 PumpA PumpA_pos, 0 TIME Ti2 DOUT X,1,1,1 
			ELSE
				PVT Z Zi, 0 TIME Ti1 DOUT X,1,0,1
				PVT Z Zi, 0 TIME Ti2 DOUT X,1,1,1
		END IF
	NEXT i
	
'correct phase every 64 repeats (if err > 5 um)
	j=j+1
	'IF (j/64 - FLOOR(j/64)) = 0
	'	THEN
	'		pos_err = DGLOBAL(2)-Z_synch
	'		IF ABS(pos_err) > 0.003
	'			THEN 
	'				offset = pos_err/75
	'				DGLOBAL(0) = DGLOBAL(0)+ pos_err/75
	'		END IF
	'		DGLOBAL(1) = 0
	'END IF

	'FORMAT PrintString, "%d\n", INTV:j
	'PRINT PrintString
WEND