' ------------------------------------------------ 
' --------------- PVT_250Hz_FastReturn.ab -----------------
' ------------------------------------------------ 
'
'
'velocity is ~150 mm/ms
'

DGLOBAL(3) = 2 'default mode of operation
mode_current = DGLOBAL(3)
DGLOBAL(0) = 0 'time offset to synchronize
DGLOBAL(1) = 0 'counter for computing <PMCD(Z)>

'User input (Z_1, PumpA_step)
Z_41 = 12.75 'slot 41 position 
DZ = 0.610		'slot separation
Nslots = 41
PumpA_step = 45/24
DT = 0.024304558/6	'~250 Hz; 1100 subharmonic of P0



'DT = 0.999998412*DT 'oscillator correction relative to Ramsey RF (351.93398 MHz)
DT = 1.00023*DT 'oscillator correction for DG535 (0.866 Hz)
Z_1 = Z_41 -(Nslots - 1)*DZ 'slot 1 position
Z_mid = Z_41 - 0.5*(Nslots - 1)*DZ 'mid-point of the stroke
Z_end = Z_41 + 0.5*DZ ' end-point of the stroke
Z_start = Z_41-(Nslots - 0.5)*DZ
Vn = DZ/DT	'velocity of sample cell


'SETGAIN <Axis>, <GainKp>, <GainKi>, <GainKpos>, <GainAff>
'SETGAIN sets all 4 parameters synchronously
'SETGAIN Z, 1780000, 10000, 56.2, 56200 original settings
SETGAIN Z, 1780000, 10000, 56.2, 56200
SETPARM Z, GainVff, 0

DIM PrintString AS STRING(80)

'Initial setup for Z axis
IF AXISFAULT(Z) <> 0 THEN
    FAULTACK Z 'Make sure any fault state is cleared.
END IF
ENABLE Z
DIM homed AS INTEGER
homed = (AXISSTATUS(Z) >> 1) BAND 1
IF NOT homed THEN 'make sure axis is homeds
    HOME Z
END IF
MOVEABS Z Z_end 'move to end of stroke position
WAIT MOVEDONE Z

DOUT X,1,0:0 'Ensure digital output is low when starting

'Find current position of PumpA
PumpA_0 = PCMD(PumpA)

'Set up for PVT calls
ABS 'Positions specified in absolute coordinates
PVT INIT TIME ABS
HALT

WHILE DIN(X,1,0)=1 'wait for clk pulse 
	DWELL 0.00025 
WEND
WHILE DIN(X,1,0)=0 'wait for clk pulse 
	DWELL 0.00025 
WEND
DGLOBAL(1) = 0 'reset PLL counter
SCOPETRIG 'Requires 0.008 s to execute?

DWELL ((5*57+42+15/2)*DT - 0.009) 'DWELL time to phase the start of the Z motion

j = 0
k = 0
PVT Z Z_end, 0 PumpA PumpA_0, 0 TIME 0.001 DOUT X,1,0,1
WHILE DGLOBAL(3) > -1 'insert IF statements to select mode; mode 1 pauses motion
	IF mode_current <> DGLOBAL(3) THEN
		mode_current = DGLOBAL(3)
		DGLOBAL(1) = 0 'reset pos_err counter
	END IF
	IF DGLOBAL(3) = 2 THEN
		REPEAT 5
			PumpA_pos = PumpA_0 + k*PumpA_step
			T_0 = T_0 + 15*DT + (42+15)*DT+DGLOBAL(0)'42+15 = 57 -> 4.33 Hz
			FOR i = 0 TO Nslots + 1
				Zi = Z_1 + (i-1)*DZ
				Ti = T_0 + i*DT
				IF i = 0 THEN
					PVT Z Z_start, 0 PumpA PumpA_pos, 0 TIME Ti DOUT X,1,0,1
				ELSEIF i = Nslots + 1 THEN
					PVT Z Z_end, 0 PumpA PumpA_pos, 0 TIME Ti DOUT X,1,1,1			
				ELSE
					PVT Z Zi, Vn PumpA PumpA_pos, 0 TIME Ti DOUT X,1,1,1		
				END IF
			NEXT i
			k = k + 1
		ENDREPEAT
	ELSEIF DGLOBAL(3) = 1 THEN
		PumpA_pos = PumpA_0 + k*PumpA_step
		T_0 = T_0 + 15*DT + (6*42+33)*DT+DGLOBAL(0) '285*DT -> 0.866 Hz
		FOR i = 0 TO Nslots + 1
			Zi = Z_1 + (i-1)*DZ
			Ti = T_0 + 6*i*DT
			IF i = 0
				THEN
					PVT Z Z_start, 0 PumpA PumpA_pos, 0 TIME Ti DOUT X,1,0,1
			ELSEIF i = Nslots + 1
				THEN
					PVT Z Z_end, 0 PumpA PumpA_pos, 0 TIME Ti DOUT X,1,1,1
					PVT Z Z_end, 0 PumpA PumpA_pos, 0 TIME Ti+(18*DT) DOUT X,1,0,1	
			ELSE
					PVT Z Zi, 0 PumpA PumpA_pos, 0 TIME (Ti-3*DT) DOUT X,1,1,1
					PVT Z Zi, 0 PumpA PumpA_pos, 0 TIME Ti DOUT X,1,1,1
					
			END IF
		NEXT i
		k = k + 1
	ELSE
		T_0 = T_0 + 15*DT + (6*42+33)*DT+DGLOBAL(0)
		PVT Z Z_41, 0 PumpA PumpA_pos, 0 TIME T_0 DOUT X,1,0,1
	END IF

	'FORMAT PrintString, "%d,%.3f,%.3f,%.3f,%.3f\n",
	'INTV:j,DBLV:T_1,DBLV:T_2,DBLV:T_3,DBLV:T_4
	'PRINT PrintString
	'FORMAT PrintString, "%d,%.3f,%.3f,%.3f,%.3f\n",
	'INTV:j,DBLV:Z_1,DBLV:Z_2,DBLV:Z_3,DBLV:Z_4
	'PRINT PrintString

		
'correct phase every 64 repeats (if err > 5 um)
	IF DGLOBAL(3) > 0 THEN
		N_correct = 64
		IF (j<>0) AND (j/N_correct - FLOOR(j/N_correct)) = 0 THEN
			pos_err = DGLOBAL(2) - Z_mid + 0.4
			IF ABS(pos_err) > 0.003 THEN 	'divide pos_err by Vmax -> 616 mm/s during back stroke
				DGLOBAL(0) = DGLOBAL(0) - pos_err/617
			END IF
			DGLOBAL(1) = 0
			FORMAT PrintString, "%d,%.3f,%.5f\r",
			INTV:j,DBLV:pos_err,DBLV:DGLOBAL(0)
			PRINT PrintString
		END IF
	END IF
	'FORMAT PrintString, "%d\n", INTV:j
	'PRINT PrintString
	j=j+1
WEND
MOVEABS Z Z_1 'Go to first slot