' ------------------------------------------------ 
' --------------- PVT_250Hz_FastReturn.ab -----------------
' ------------------------------------------------ 
'
'
'velocity is ~150 mm/ms
'


DGLOBAL(0) = 0 'time offset to synchronize
DGLOBAL(1) = 0 'counter for computing <PMCD(Z)>

Z_0 = 12.94 '13.19 'starting Z position
DZ = 0.610		'slot separation
DT = 0.024304558/6	'~250 Hz
DT = 0.999998412*DT 'oscillator correction
Nslots = 41

Vn = -1*DZ/DT	'velocity of sample cell

'Z_synch = Z_0-0.3 'synch location

SCOPETRIG
DWELL 0.003


'SETGAIN <Axis>, <GainKp>, <GainKi>, <GainKpos>, <GainAff>
'SETGAIN sets all 4 parameters synchronously
SETGAIN Z, 1780000, 10000, 100, 56200
SETPARM Z, GainVff, 2371

DIM PrintString AS STRING(80)

POSOFFSET SET PumpA, 0
SETEXTPOS PumpA, 0
PumpA_0 = PCMD(PumpA)

'Initial setup
IF AXISFAULT(Z) <> 0 THEN
    FAULTACK Z 'Make sure any fault state is cleared.
END IF
ENABLE Z
DIM homed AS INTEGER
homed = (AXISSTATUS(Z) >> 1) BAND 1
IF NOT homed THEN 'make sure axis is homeds
    HOME Z
END IF
MOVEABS Z Z_0 - (Nslots-0.5)*DZ ' + DZ 'Got to starting position
WAIT MOVEDONE Z

'RAMP TIME PumpA 0.038
'RAMP RATE PumpA 820000

ABS 'Positions specified in absolute coordinates
PVT INIT TIME ABS
HALT

WHILE DIN(X,1,0)=0 'wait for clk pulse 
	DWELL 0.00025 
WEND

DWELL 0.252



PVT Z (Z_0 - (Nslots-0.5)*DZ), 0 PumpA 0, 0 TIME 0.0001 DOUT X,1,0,1

j = 0
WHILE 1
	PumpA_pos = PumpA_0 + j*45
	T_0 = 15*DT + j*57*DT + DGLOBAL(0) ' 57 -> 4.33 Hz
	FOR i = -1 TO Nslots 
		Ti = T_0 + (i+1)*DT
		Zi = Z_0 - i*DZ
		IF i = -1
			THEN
				PVT Z Zi, 0 PumpA PumpA_pos, 0 TIME Ti DOUT X,1,1,1
		ELSEIF i = Nslots 
			THEN
				PVT Z Zi, 0 PumpA PumpA_pos, 0 TIME Ti DOUT X,1,0,1
				IF j = 0 THEN
					DGLOBAL(1) = 0 'reset PLL counter
				END IF				
		ELSE
				PVT Z Zi, Vn PumpA PumpA_pos, 0 TIME Ti DOUT X,1,1,1
				
		END IF
	NEXT i

	'FORMAT PrintString, "%d,%.3f,%.3f,%.3f,%.3f\n",
	'INTV:j,DBLV:T_1,DBLV:T_2,DBLV:T_3,DBLV:T_4
	'PRINT PrintString
	'FORMAT PrintString, "%d,%.3f,%.3f,%.3f,%.3f\n",
	'INTV:j,DBLV:Z_1,DBLV:Z_2,DBLV:Z_3,DBLV:Z_4
	'PRINT PrintString

		
'correct phase every 64 repeats (if err > 5 um)

	IF (j<>0) AND (j/64 - FLOOR(j/64)) = 0
		THEN
			pos_err = DGLOBAL(2)
			IF ABS(pos_err) > 0.003
				THEN 	'divide pos_err by Vmax
					DGLOBAL(0) = DGLOBAL(0)+ pos_err/606
			END IF
			DGLOBAL(1) = 0
	FORMAT PrintString, "%d,%.3f,%.5f\r",
	INTV:j,DBLV:DGLOBAL(2),DBLV:DGLOBAL(0)
	PRINT PrintString
	END IF

	'FORMAT PrintString, "%d\n", INTV:j
	'PRINT PrintString
	j=j+1
WEND