VAL.filename = '//mx340hs/data/anfinrud_1906/Archive/NIH.TEMP.VAL.txt'
RBV.filename = '//mx340hs/data/anfinrud_1906/Archive/NIH.TEMP.RBV.txt'
I.filename = '//mx340hs/data/anfinrud_1906/Archive/NIH.TEMP.I.txt'
P.filename = '//mx340hs/data/anfinrud_1906/Archive/NIH.TEMP.P.txt'
i.filename = '/net/femto/C/All Projects/APS/Experiments/2019.05/Test/Archive/NIH.TEMP.i.txt'