Ensemble.ip_address = 'nih-instrumentation.aps.anl.gov:2000'
MicroscopeCamera.ImageWindow.Center = (680, 512)
MicroscopeCamera.Mirror = True
MicroscopeCamera.NominalPixelSize = 0.000526
MicroscopeCamera.Orientation = 0
MicroscopeCamera.camera.IP_addr = 'id14b-prosilica1.cars.aps.anl.gov'
MicroscopeCamera.x_scale = 1.0
MicroscopeCamera.y_scale = 1.0
MicroscopeCamera.z_scale = 1.0
WideFieldCamera.ImageWindow.Center = (680, 512)
WideFieldCamera.Mirror = False
WideFieldCamera.NominalPixelSize = 0.00465
WideFieldCamera.Orientation = 0
WideFieldCamera.camera.IP_addr = 'id14b-prosilica2.cars.aps.anl.gov'
WideFieldCamera.x_scale = 1.0
WideFieldCamera.y_scale = 1.0
WideFieldCamera.z_scale = 1.0
laser_scope.ip_address = 'id14l-scope.cars.aps.anl.gov:2000'
rayonix_detector.ip_address = 'mx340hs.cars.aps.anl.gov:2222'
sample.phi_motor_name = 'Phi'
sample.phi_scale = 1.0
sample.rotation_center = (0.0, 0.0)
sample.x_motor_name = 'GonX'
sample.x_scale = 1.0
sample.xy_rotating = True
sample.y_motor_name = 'GonY'
sample.y_scale = 1.0
sample.z_motor_name = 'GonZ'
sample.z_scale = 1.0
timing_system.ip_address = 'id14timing2.cars.aps.anl.gov:2000'
xray_scope.ip_address = 'id14b-xscope.cars.aps.anl.gov:2000'