PROGRAM
	ABS
	PVT INIT TIME ABS
	VELOCITY ON
	HALT
	SCOPEBUFFER 1200
	SCOPETRIGPERIOD -2	' -4 (-2) corresponds to 4 (2) kHz
	SCOPETRIG
	
	DT = 0.024
	DX = 0.5
	Ti = 0.001
	
	Ti = Ti + DT
	Xi = Xi + DX
	PVT X Xi,0 TIME Ti
	Ti = Ti + 3*DT
	PVT X Xi,0 TIME Ti
	Ti = Ti + DT
	Xi = Xi + DX
	PVT X Xi,0 TIME Ti
	Ti = Ti + 3*DT
	PVT X Xi,0 TIME Ti
	Ti = Ti + DT
	Xi = Xi + DX
	PVT X Xi,0 TIME Ti
	Ti = Ti + 3*DT
	PVT X Xi,0 TIME Ti
	Ti = Ti + 4*DT
	Xi = Xi -3*DX
	PVT X Xi,0 TIME Ti
	
	START
END PROGRAM