#!/bin/bash -l
# Mac OS X startup script for Time-resolved Wide-Angle X-ray scattering software
# This needs to be located in the directory basename.app/Contents/MacOS
# The basename.app directory is created with the "Build Applet" utility
# include in MacPython.

# The -l (login) option makes sure that the environment is the same as for
# an interactive shell. 
# If MacPython is installed it modifies the PATH environment variable in
# ~/.bash_profile such that "python" refers to the MacPython version, rather
# than Mac OS X's built-in version of Python.

# Use this to check which version of python is used:
# which python > /tmp/ImageViewer.log

# Friedrich Schotte, 24 Jan 2009

dir=`dirname "$0"`/../../..
prog=`basename "$0"`
PYTHONPATH="${dir}:$PYTHONPATH"
exec python "$dir/$prog.py" "$1" "$2" 2>&1 > /tmp/ImageViewer.log
# Append this is inspect error messages: 2>&1 > /tmp/ImageViewer.log
